---
abstract: 'Safely modify the QUERY_STRING of a PSGI request'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Rewrite-Query
recommends:
  Plack::Middleware::Rewrite: 0
requires:
  Plack: 1.0
resources:
  bugtracker: https://github.com/nichtich/Plack-Middleware-Rewrite-Query/issues
  homepage: https://github.com/nichtich/Plack-Middleware-Rewrite-Query
  repository: https://github.com/nichtich/Plack-Middleware-Rewrite-Query.git
version: 0.1.0
